kind: Pod
apiVersion: v1
metadata:
  name: nginx
  labels:
    name: frontend
    environment: dev
    project : expense
    component: frontend
    
spec:
  containers:
  - name: nginx
    image: nginx